---
- name: Start IIS Services on Windows Hosts and Show W3SVC State
  hosts: all
  gather_facts: false

  tasks:
    - name: Start IIS using iisreset
      ansible.windows.win_command: iisreset /start
      
    - name: Start W3SVC service
      ansible.windows.win_service:
      name: W3SVC
      state: started

    - name: Show state of W3SVC service after start
      ansible.windows.win_service:
        name: W3SVC
      register: w3svc_status_after

    - name: Display only W3SVC service state after start
      ansible.builtin.debug:
        msg: "{{ w3svc_status_after.state }}"
