---
- name: Show W3SVC state after Start IIS Services on Windows Hosts
  hosts: all
  gather_facts: false

  tasks:
    - name: Start IIS using iisreset
      ansible.windows.win_command: iisreset /start

    - name: Show state of W3SVC service after stop
      ansible.windows.win_service:
        name: W3SVC
      register: w3svc_status_after

    - name: Display only W3SVC service state after start
      ansible.builtin.debug:
        msg: "{{ w3svc_status_after.state }}"
