---
- name: Main Playbook to include all YAML scripts
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    # Define any common variables here if needed
  tasks:
    - name: Include all playbook YAML scripts
      include_tasks: "{{ item }}"
      loop:
        - uptime.yml
        - ip.yml
