---
- name: Start IIS Service on Windows
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Start World Wide Web Publishing Service (W3SVC)
      win_service:
        name: W3SVC
        state: started
