---
- name: Stop IIS Services on Windows Hosts
  hosts: all
  gather_facts: false

  tasks:
    - name: Stop IIS (W3SVC) and WAS services
      ansible.windows.win_powershell:
        script: |
          Stop-Service -Name 'W3SVC','WAS' -Force
