- name: Check system uptime on all hosts
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Get system uptime
      ansible.builtin.command: uptime
      register: uptime_output

    - name: Show uptime result
      ansible.builtin.debug:
        var: uptime_output.stdout
