- name: Check system uptime on all hosts

  tasks:
    - name: Get system uptime
      ansible.builtin.command: uptime
      register: uptime_output

    - name: Show uptime result
      ansible.builtin.debug:
        var: uptime_output.stdout
